### ISSUE TITLE
Get the songs in plain text format

### ISSUE THREAD

**Issue by tshrinivasan** [Tpj-root/site_cloner#1]
Thanks for the code.

Please add a feature to get the songs in plain text and store in a text file.
extract the songs with beautiful soup and may need some data cleaning.

**Comment by Tpj-root** [comment]
Bro, the code was updated.
`bash lyrics_html2txt.sh`

It will convert all the HTML into text files.
Some data cleaning processes will be added in the future in that file `html2txt.py`, so it won't affect the bash script.
Try the script and give me your suggestions.
